FROM resin/armv7hf-debian:jessie

# Install mosquitto
RUN apt-get update && apt-get install -y wget
#RUN wget http://repo.mosquitto.org/debian/mosquitto-repo.gpg.key
#RUN apt-key add mosquitto-repo.gpg.key
#RUN cd /etc/apt/sources.list.d/ && wget http://repo.mosquitto.org/debian/mosquitto-jessie.list
#RUN apt-get update
RUN apt-get install -y mosquitto

# Expose port 1883
EXPOSE 1883

ENTRYPOINT ["mosquitto"]
